a = int(input("Podaj liczbę: "))

while a >= 1000:
    a = a - 1000
    print("M", end="")
if a >= 900:
    a = a - 900
    print("CM", end="")
if a >= 500:
    a = a - 500
    print("D", end="")
if a >= 400:
    a = a - 400
    print("CD", end="")
while a >= 100:
    a = a - 100
    print("C", end="")
if a >= 90:
    a = a - 90
    print("XC", end="")
if a >= 50:
    a = a - 50
    print("L", end="")
if a >= 40:
    a = a - 40
    print("XL", end="")
while a >= 10:
    a = a - 10
    print("X", end="")
if a >= 9:
    a = a - 9
    print("IX", end="")
if a >= 5:
    a = a - 5
    print("V", end="")
if a >= 4:
    a = a - 4
    print("IV", end="")
while a >= 1:
    a = a - 1
    print("I", end="")
